language: python
python:
  - 2.7
install:
  - pip install pytest
jobs:
  include:
    - stage: test
      script: python test_sample.py
    - stage: QA
      script: python test_sample.py

notifications:
  slack: rcsousa-home-lab:USIyf5RINv2cI0B5JvQXqkgg
